/**
 * EXPO-WIDGET-PIN — Android-only module that wraps
 * `AppWidgetManager.requestPinAppWidget` to let the app trigger the
 * native widget-placement dialog (Android 8.0+ / API 26+).
 *
 * JS API:
 *   - `isPinSupported()` → boolean. Quick check before showing pin UI.
 *   - `isWidgetPlaced(className)` → boolean. True if the user has at
 *     least one instance of the widget on their home screen.
 *   - `requestPin(className)` → Promise<boolean>. Shows the native pin
 *     dialog. Resolves true if the launcher accepted, false if
 *     unsupported or cancelled.
 *
 * The `className` must be the fully-qualified Java class name of the
 * AppWidgetProvider — for Puppy Prep this is
 *   `com.puppyprep.app.widget.TodayCalendar`
 * (generated by react-native-android-widget's config plugin at build time).
 *
 * iOS + web: every function is a graceful no-op that returns false.
 */
import { Platform } from 'react-native';

interface ExpoWidgetPinModuleInterface {
  isPinSupported(): boolean;
  isWidgetPlaced(widgetClassName: string): boolean;
  requestPin(widgetClassName: string): Promise<boolean>;
}

const stub: ExpoWidgetPinModuleInterface = {
  isPinSupported: () => false,
  isWidgetPlaced: () => false,
  requestPin: async () => false,
};

// Lazy-load the native module only on Android so iOS + web builds don't
// trip on the missing binding.
let impl: ExpoWidgetPinModuleInterface = stub;
if (Platform.OS === 'android') {
  try {
    // require-based so Metro/esbuild don't statically resolve on web
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { requireNativeModule } = require('expo-modules-core');
    impl = requireNativeModule('ExpoWidgetPin') as ExpoWidgetPinModuleInterface;
  } catch {
    // Module not in bundle (e.g. running in Expo Go) — stay on stub
    impl = stub;
  }
}

export default impl;
