/**
 * USE WIDGET STATUS
 *
 * Detects whether the Puppy Prep home-screen widget is currently placed
 * on the user's launcher. Auto-refreshes when the app comes back to the
 * foreground (typical case: user added the widget, switches back to app).
 *
 * Android-only. Always returns `isPlaced: false` on iOS / web / Expo Go.
 */
import { useEffect, useState, useCallback, useRef } from 'react';
import { AppState, Platform } from 'react-native';
import WidgetPin from '../../modules/expo-widget-pin';

/** Widget provider class name — auto-generated by react-native-android-widget config plugin */
export const TODAY_WIDGET_CLASS = 'com.puppyprep.app.widget.TodayCalendar';

interface WidgetStatus {
  /** Whether the widget is currently on the home screen */
  isPlaced: boolean;
  /** Whether the OS supports programmatic pinning (Android 8.0+ launcher) */
  canPin: boolean;
  /** Force a refresh of the status */
  refresh: () => void;
  /** Trigger the native pin dialog. Resolves after the launcher shows it. */
  requestPin: () => Promise<boolean>;
}

export function useWidgetStatus(): WidgetStatus {
  const [isPlaced, setIsPlaced] = useState(false);
  const [canPin, setCanPin] = useState(false);
  const pollingRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const refresh = useCallback(() => {
    if (Platform.OS !== 'android') return;
    try {
      setIsPlaced(WidgetPin.isWidgetPlaced(TODAY_WIDGET_CLASS));
      setCanPin(WidgetPin.isPinSupported());
    } catch {
      setIsPlaced(false);
      setCanPin(false);
    }
  }, []);

  // Initial + foreground-driven refresh
  useEffect(() => {
    refresh();
    const sub = AppState.addEventListener('change', (state) => {
      if (state === 'active') refresh();
    });
    return () => sub.remove();
  }, [refresh]);

  /**
   * Trigger the native pin dialog, then poll for ~4 seconds to detect
   * when the user confirms placement. Without this, the UI wouldn't
   * update until the user tabs away + back — the widget IS placed but
   * our state still says it isn't.
   */
  const requestPin = useCallback(async (): Promise<boolean> => {
    if (Platform.OS !== 'android') return false;
    const ok = await WidgetPin.requestPin(TODAY_WIDGET_CLASS);
    if (!ok) return false;

    // Poll every 300ms up to ~4 seconds to catch placement
    if (pollingRef.current) clearInterval(pollingRef.current);
    let ticks = 0;
    pollingRef.current = setInterval(() => {
      ticks++;
      const placed = WidgetPin.isWidgetPlaced(TODAY_WIDGET_CLASS);
      if (placed || ticks > 13) {
        if (placed) setIsPlaced(true);
        if (pollingRef.current) {
          clearInterval(pollingRef.current);
          pollingRef.current = null;
        }
      }
    }, 300);
    return true;
  }, []);

  // Clean up any straggling poll interval
  useEffect(() => {
    return () => {
      if (pollingRef.current) clearInterval(pollingRef.current);
    };
  }, []);

  return { isPlaced, canPin, refresh, requestPin };
}
